import React, { useEffect, useState } from 'react';
import { Amplify, API, Auth } from 'aws-amplify';

/*
 * Configure Amplify here.  At runtime the values for region, user pool and
 * API endpoint will be injected via environment variables (for example using
 * the `aws-exports.js` file generated by `amplify init` or via a config
 * fetched from S3).  The example below uses placeholders.
 *
 * In some bundlers (e.g. Vite or plain webpack) the global `process` object
 * may be undefined.  To avoid a `ReferenceError` we fall back to an empty
 * object when `process` is not available.  This allows the application to
 * start even if no environment variables are injected.
 */
const env = typeof process !== 'undefined' && process.env ? process.env : {};

Amplify.configure({
  Auth: {
    region: env.REACT_APP_REGION || 'us-east-1',
    userPoolId: env.REACT_APP_USER_POOL_ID || '',
    userPoolWebClientId: env.REACT_APP_USER_POOL_CLIENT || '',
  },
  API: {
    endpoints: [
      {
        name: 'EducationApi',
        endpoint: env.REACT_APP_API_URL || 'http://127.0.0.1:3000',
        region: env.REACT_APP_REGION || 'us-east-1',
      },
    ],
  },
});

export default function App() {
  const [lessons, setLessons] = useState(null);
  const [loading, setLoading] = useState(false);

  // Example: fetch today’s lessons when the component mounts
  useEffect(() => {
    const fetchLessons = async () => {
      setLoading(true);
      try {
        const res = await API.get('EducationApi', '/lessons', {});
        setLessons(res);
      } catch (err) {
        console.error('Failed to fetch lessons', err);
      } finally {
        setLoading(false);
      }
    };
    fetchLessons();
  }, []);

  return (
    <main style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>Education Platform</h1>
      {loading && <p>Loading today’s lesson…</p>}
      {lessons && (
        <div>
          <h2>{lessons.title}</h2>
          <p>{lessons.description}</p>
          {/* Render questions, games and audio links here */}
        </div>
      )}
    </main>
  );
}